import subprocess
args_list = [
            #   ['python', 'fibergeneration.py',
            #   '--suffix', 'alltracts_HCP_trained',
            #   '--model_path', '/data04/junyi/models/whole_model.pt',
            #   '--data_path', '/data01/junyi/datasets/HCP_100',
            #   '--sub_num', '100',
            #   '--device', 'cuda:2',
            #   '--batch_size', '2'],
            #   ['python', 'fibergeneration.py',
            #   '--suffix', 'FA_only_HCP_trained',
            #   '--model_path', '/data04/junyi/models/FA_only_model.pt',
            #   '--data_path', '/data01/junyi/datasets/HCP_100',
            #   '--sub_num', '100',
            #   '--device', 'cuda:2',
            #   '--batch_size', '2'],
              # ['python', 'fibergeneration.py',
              # '--suffix', 'alltracts_HCP_test',
              # '--model_path', '/data04/junyi/models/whole_model.pt',
              # '--data_path', '/data04/junyi/Datasets/HCP_test',
              # '--sub_num', '50',
              # '--device', 'cuda:0',
              # '--batch_size', '2'],
              # ['python', 'fibergeneration.py',
              # '--suffix', 'FA_only_HCP_test',
              # '--model_path', '/data04/junyi/models/FA_only_model.pt',
              # '--data_path', '/data04/junyi/Datasets/HCP_test',
              # '--sub_num', '50',
              # '--device', 'cuda:0',
              # '--batch_size', '4'],
              # ['python', 'fibergeneration.py',
              # '--suffix', 'alltracts_ABCD',
              # '--model_path', '/data04/junyi/models/whole_model.pt',
              # '--data_path', '/data04/junyi/Datasets/ABCD_Reg/data/DWI',
              # '--sub_num', '50',
              # '--device', 'cuda:0',
              # '--batch_size', '2'],
              # ['python', 'fibergeneration.py',
              # '--suffix', 'FA_only_ABCD',
              # '--model_path', '/data04/junyi/models/FA_only_model.pt',
              # '--data_path', '/data04/junyi/Datasets/ABCD_Reg/data/DWI',
              # '--sub_num', '50',
              # '--device', 'cuda:0',
              # '--batch_size', '4'],
              # ['python', 'fibergeneration.py',
              # '--suffix', 'alltracts_PPMI',
              # '--model_path', '/data04/junyi/models/whole_model.pt',
              # '--data_path', '/data04/junyi/Datasets/PPMI_Reg/data/DWI',
              # '--sub_num', '50',
              # '--device', 'cuda:0',
              # '--batch_size', '2'],
              # ['python', 'fibergeneration.py',
              # '--suffix', 'FA_only_PPMI',
              # '--model_path', '/data04/junyi/models/FA_only_model.pt',
              # '--data_path', '/data04/junyi/Datasets/PPMI_Reg/data/DWI',
              # '--sub_num', '50',
              # '--device', 'cuda:2',
              # '--batch_size', '4'],
              
              # ['python', 'fibergeneration.py',
              # '--suffix', 'tract1_HCP_trained',
              # '--model_path', '/data04/junyi/models/tracts_1_model.pt',
              # '--data_path', '/data01/junyi/datasets/HCP_100',
              # '--sub_num', '50',
              # '--device', 'cuda:2',
              # '--batch_size', '4',
              # '--tracts_num', '1'],
              ['python', 'fibergeneration.py',
              '--suffix', 'tract4_HCP_test',
              '--model_path', '/data04/junyi/models/tracts_4_model.pt',
              '--data_path', '/data04/junyi/Datasets/HCP_test',
              '--sub_num', '50',
              '--device', 'cuda:2',
              '--batch_size', '4',
              '--tracts_num', '4'],
              ['python', 'fibergeneration.py',
              '--suffix', 'tract17_HCP_test',
              '--model_path', '/data04/junyi/models/tracts_17_model.pt',
              '--data_path', '/data04/junyi/Datasets/HCP_test',
              '--sub_num', '50',
              '--device', 'cuda:2',
              '--batch_size', '4',
              '--tracts_num', '17'],
              ]
for args in args_list:
    subprocess.run(args)